// ════════════════════════════════════════════════════════════════
//  KeyZen — Exercise Database
//  140 exercises total:  Easy ×50  |  Normal ×50  |  Hard ×40
// ════════════════════════════════════════════════════════════════

const EX = {
easy:[
  {id:'e01',title:'Home Row Basics',      text:'asd fgh jkl asd fgh jkl sad fla jag ash fad lag jak asd fgh jkl'},
  {id:'e02',title:'Simple Three-Letter',  text:'the cat sat on the mat and the dog ran to the big box by the log'},
  {id:'e03',title:'Short Common Words',   text:'I am a cat and you are a dog we can all run and play in the sun all day'},
  {id:'e04',title:'Basic Sentence',       text:'The sun is hot. The sky is blue. The grass is green. The tree is tall.'},
  {id:'e05',title:'Color Words',          text:'red blue green yellow pink black white orange purple gray brown gold'},
  {id:'e06',title:'Number Words',         text:'one two three four five six seven eight nine ten eleven twelve twenty'},
  {id:'e07',title:'Days of the Week',     text:'Monday Tuesday Wednesday Thursday Friday Saturday Sunday Monday Friday'},
  {id:'e08',title:'Animal Names',         text:'cat dog bird fish cow pig hen fox bear wolf deer lamb owl duck frog'},
  {id:'e09',title:'Fruit Names',          text:'apple mango banana grape lemon lime peach plum melon cherry kiwi pear'},
  {id:'e10',title:'Simple Verbs',         text:'run jump sit eat sleep walk talk read write draw sing dance play swim'},
  {id:'e11',title:'Family Words',         text:'mom dad son girl boy baby sister brother uncle aunt family home child'},
  {id:'e12',title:'Body Parts',           text:'head eye ear nose lip arm hand leg foot back neck chin wrist knee toe'},
  {id:'e13',title:'School Words',         text:'pen book desk chair class test read write math art grade school teacher'},
  {id:'e14',title:'Greetings',            text:'hello hi hey good day good morning good night how are you thank you bye'},
  {id:'e15',title:'Opposite Pairs',       text:'big small hot cold fast slow old new high low left right up down dark light'},
  {id:'e16',title:'Simple Commands',      text:'open the door close the window turn off the light put it on the table now'},
  {id:'e17',title:'At the Park',          text:'the kids play in the park they run on the grass and jump in the mud all day'},
  {id:'e18',title:'Weather Words',        text:'sun rain snow wind fog ice hail cloud storm calm warm cool hot cold dry wet'},
  {id:'e19',title:'Food Words',           text:'rice soup milk eggs bread fish meat cake pie jam salt oil tea water juice'},
  {id:'e20',title:'Transportation',       text:'car bus van bike truck ship jet boat cab train tram walk ride fly drive'},
  {id:'e21',title:'In the Kitchen',       text:'the cup is on the shelf the pan is on the stove the bowl has soup in it'},
  {id:'e22',title:'My Morning',           text:'i wake up and brush my teeth then i eat some toast and drink my tea and go'},
  {id:'e23',title:'Simple Story',         text:'a boy had a red ball he threw it at the wall and it came back to him fast'},
  {id:'e24',title:'Short Questions',      text:'what is your name how old are you where do you live do you like cats or dogs'},
  {id:'e25',title:'Two-Letter Words',     text:'an am at as if in is it of on or up us to do go he me my no we be by so'},
  {id:'e26',title:'Garden Time',          text:'the rose is red the leaf is green the stem is thin and the bud is very small'},
  {id:'e27',title:'Long Vowel Words',     text:'cake lake make take bake fake tape cape date fate gate hate late wave save gave'},
  {id:'e28',title:'Short Vowel Drill',    text:'cat bat hat mat rat sat fat pat tap cap map nap rap lap gap wax tax sack back'},
  {id:'e29',title:'What I See',           text:'i see a tree i see a bird i see the sky i see the sun i see the clouds above'},
  {id:'e30',title:'My Pet',              text:'my dog is brown and soft he likes to run and fetch the ball in the yard each day'},
  {id:'e31',title:'Months of Year',       text:'January February March April May June July August September October November December'},
  {id:'e32',title:'Question Words',       text:'who what when where why how which whose how much how many how long how often'},
  {id:'e33',title:'Bedroom Scene',        text:'the bed is soft the lamp is dim the book is on the shelf the cat is fast asleep'},
  {id:'e34',title:'Simple Rhyme',         text:'the cat sat on the mat the bat is at the flat the fat rat sat on that old mat'},
  {id:'e35',title:'Counting Objects',     text:'one hen two hens three hens four hens five hens six hens seven hens eight hens'},
  {id:'e36',title:'At the Store',         text:'i went to the shop to buy milk bread eggs and some fruit for the week ahead'},
  {id:'e37',title:'Easy Phrases',         text:'good job well done nice try keep it up you can do it great work stay strong'},
  {id:'e38',title:'Keyboard Row 1',       text:'qwertyuiop qwer tyui qwerty uiop qwer tyuiop qwertyui qwer tyuiop qwertyuiop'},
  {id:'e39',title:'Keyboard Row 2',       text:'asdfghjkl asdf ghjkl asdfg hjkl asdfy ghjkl asdf ghjkl asdfgh jkl asdfghjkl'},
  {id:'e40',title:'Easy Wrap-Up',         text:'type each word with care keep your eyes on the screen and your fingers on the keys'},
  {id:'e41',title:'Shape Names',        text:'circle square triangle oval star heart diamond arrow cross ring cone cube sphere line point'},
  {id:'e42',title:'The Four Seasons',   text:'spring brings warm rain summer brings long hot days autumn turns all leaves red winter brings cold snow'},
  {id:'e43',title:'Clothing Words',     text:'shirt pants dress coat shoes socks hat cap scarf belt boots gloves bag tie watch ring band jacket'},
  {id:'e44',title:'Rooms at Home',      text:'hall room bath door wall roof floor bed sofa lamp desk sink stair shelf window yard porch gate fence'},
  {id:'e45',title:'Nature Words',       text:'tree leaf bark root seed soil rain wind river lake hill sand cloud fog dew moss stone mud sky fire'},
  {id:'e46',title:'Math Words',         text:'add sum plus minus equal zero half twice more less total count number value whole part share even odd'},
  {id:'e47',title:'Feelings',           text:'glad sad mad calm shy bold kind warm rude brave proud tense happy grumpy jolly tired bored eager free'},
  {id:'e48',title:'Toys and Play',      text:'ball doll kite drum top bike sled rope bat cube card dice lego game board paint clay block puzzle jump'},
  {id:'e49',title:'Jobs We Know',       text:'cook nurse chef pilot guard clerk baker judge actor singer coach tutor poet farmer driver vet plumber'},
  {id:'e50',title:'Easy Grand Finale',  text:'keep your back straight your wrists flat and your eyes on the screen every single keystroke matters a lot'}
],
normal:[
  {id:'n01',title:'Morning Routine',         text:'Every morning I wake up at seven, brush my teeth, make coffee, and review my tasks for the day ahead.'},
  {id:'n02',title:'Technology Today',        text:'Technology changes faster than ever before. New devices appear each year, reshaping how we work, learn, and connect.'},
  {id:'n03',title:'Importance of Reading',   text:'Reading improves vocabulary, sharpens the mind, and builds empathy. Even fifteen minutes a day can make a real difference.'},
  {id:'n04',title:'Fitness Benefits',        text:'Regular exercise reduces stress, boosts energy, and improves sleep quality. You do not need a gym; a daily walk works wonders.'},
  {id:'n05',title:'Learning New Skills',     text:'Learning a new skill requires patience and daily practice. Start small, stay consistent, and celebrate every tiny milestone.'},
  {id:'n06',title:'City Life',              text:'Living in a busy city offers culture, career opportunities, and diverse cuisine, but also noise, high rent, and constant crowds.'},
  {id:'n07',title:'The Ocean',              text:'The ocean covers more than seventy percent of Earth\'s surface. Its depths remain largely unexplored, hiding undiscovered creatures.'},
  {id:'n08',title:'Digital Privacy',        text:'Protecting your digital privacy means using strong passwords, enabling two-factor authentication, and being careful on social media.'},
  {id:'n09',title:'Cooking at Home',        text:'Cooking at home saves money and lets you control ingredients. Start with simple recipes and build confidence in the kitchen.'},
  {id:'n10',title:'Sleep Science',          text:'Adults need between seven and nine hours of sleep per night. Poor sleep affects memory, mood, immune function, and heart health.'},
  {id:'n11',title:'Climate Change',         text:'Rising global temperatures are causing ice caps to melt, sea levels to rise, and extreme weather events to become more frequent.'},
  {id:'n12',title:'Artificial Intelligence',text:'Artificial intelligence is transforming healthcare, finance, and education. It can diagnose diseases, detect fraud, and generate content.'},
  {id:'n13',title:'Power of Habits',        text:'Your habits define your life more than your intentions do. Small, consistent actions compounded over years produce extraordinary results.'},
  {id:'n14',title:'Remote Work',            text:'Remote work offers flexibility and eliminates the commute, but requires strong self-discipline, clear boundaries, and focused routines.'},
  {id:'n15',title:'Social Media Effects',   text:'Social media connects billions of people but also contributes to anxiety, misinformation, and shortened attention spans in all ages.'},
  {id:'n16',title:'Space Exploration',      text:'Humans have walked on the Moon and sent probes beyond our solar system. The next frontier is Mars and deep space colonization.'},
  {id:'n17',title:'Financial Literacy',     text:'Understanding compound interest, budgeting, and investing early can be the difference between financial freedom and lifelong money stress.'},
  {id:'n18',title:'Mental Health Matters',  text:'Mental health is just as important as physical health. Talking openly about anxiety and depression helps reduce stigma for everyone.'},
  {id:'n19',title:'Art of Listening',       text:'Truly listening means giving full attention, not planning your response while they speak. Good listeners are rare and deeply valued.'},
  {id:'n20',title:'Sustainable Living',     text:'Reducing plastic waste, choosing public transport, and buying locally are simple ways to make a real contribution to the planet.'},
  {id:'n21',title:'Creative Writing',       text:'Writing fiction develops creativity, emotional intelligence, and the ability to see the world from entirely different perspectives.'},
  {id:'n22',title:'History Lesson',         text:'Studying past civilizations teaches which structures and decisions lead to prosperity or collapse. Patterns from history echo in today.'},
  {id:'n23',title:'Value of Silence',       text:'In a world flooded with noise, silence has become a luxury. Sitting quietly even briefly restores clarity and reduces overload.'},
  {id:'n24',title:'Entrepreneurship',       text:'Starting a business demands resilience, creativity, and tolerance for uncertainty. Most successful entrepreneurs failed multiple times first.'},
  {id:'n25',title:'Language Learning',      text:'Learning a second language rewires the brain, delays cognitive decline, and opens doors to cultures and careers monolingual people miss.'},
  {id:'n26',title:'Photography Basics',     text:'Good photography is about light, composition, and timing more than equipment. A smartphone used with intent beats an expensive camera.'},
  {id:'n27',title:'Teamwork Principles',    text:'Effective teams communicate clearly, respect diverse viewpoints, and hold each member accountable without resorting to blame or avoidance.'},
  {id:'n28',title:'Joy of Travel',          text:'Travel forces you out of routine, challenges assumptions, and introduces unexpected moments of wonder that remind you how vast the world is.'},
  {id:'n29',title:'Nutrition Basics',       text:'A balanced diet includes proteins, healthy fats, complex carbohydrates, vitamins, and minerals. Processed food carries long-term health costs.'},
  {id:'n30',title:'Critical Thinking',      text:'Critical thinking means questioning assumptions, evaluating evidence, and considering alternatives before drawing conclusions about anything.'},
  {id:'n31',title:'Music and the Mind',     text:'Listening to music activates multiple brain regions at once. Playing an instrument strengthens memory, coordination, and mathematical reasoning.'},
  {id:'n32',title:'Animal Intelligence',    text:'Crows solve multi-step puzzles, dolphins use names for each other, and elephants grieve their dead. Animal intelligence is surprisingly widespread.'},
  {id:'n33',title:'Punctuation Practice',   text:'Wait — have you seen this? It\'s incredible! She said, "I\'ll be there by noon." However; the train was late, so she arrived at 1:45 p.m.'},
  {id:'n34',title:'Mixed Numbers',          text:'In 2024, over 5 billion people used the internet daily. By 2030, that could reach 7.5 billion, nearly 90% of the projected global population.'},
  {id:'n35',title:'Email Writing',          text:'Dear Mr. Johnson, I am writing to follow up on our meeting last Tuesday. Please find the revised proposal attached. I look forward to your feedback.'},
  {id:'n36',title:'Product Description',    text:'The KeyZen Pro Keyboard features ultra-low actuation, per-key RGB lighting, and an aluminum frame. It connects via USB-C or Bluetooth 5.2.'},
  {id:'n37',title:'Weather Report',         text:'Temperatures will reach 28 degrees Celsius on Thursday with light winds from the southwest. Expect scattered showers and clearing by evening.'},
  {id:'n38',title:'Recipe Instructions',    text:'Preheat the oven to 180 degrees. Mix 200g flour, 100g butter, and 80g sugar. Add two eggs and fold gently until a smooth dough forms.'},
  {id:'n39',title:'Book Review',            text:'This novel weaves themes of identity, loss, and redemption across three generations. The prose is precise yet poetic, making it hard to put down.'},
  {id:'n40',title:'Normal Wrap-Up',         text:'Consistent daily practice is the fastest path to improvement. Set a goal, track your progress, and never compare your beginning to someone else\'s middle.'},
  {id:'n41',title:'Power of Rest',      text:'Rest is not laziness. Strategic recovery lets the brain consolidate learning, repair tissue, and return sharper and stronger than before.'},
  {id:'n42',title:'Digital Detox',      text:'Taking regular breaks from screens reduces eye strain, improves sleep quality, and restores scattered attention. One screen-free hour each evening makes a difference.'},
  {id:'n43',title:'Design Thinking',    text:'Design thinking centres on the user: empathize with their needs, define the core problem, ideate broadly, prototype quickly, and test with real people often.'},
  {id:'n44',title:'Art of Deep Focus',  text:'Deep work is the ability to concentrate without distraction on a cognitively demanding task. It is increasingly rare and increasingly valuable in the modern economy.'},
  {id:'n45',title:'Cooking as Science', text:'Cooking is applied chemistry. Heat denatures proteins, salt draws out moisture, acid brightens flavors, and fat carries aromatic compounds directly to your taste receptors.'},
  {id:'n46',title:'Keyboard Mastery',   text:'Touch typing lets you focus on ideas rather than keys. Accuracy matters more than speed: a precise typist at sixty WPM beats a sloppy one at ninety every time.'},
  {id:'n47',title:'Time Management',    text:'The Pomodoro technique divides work into 25-minute focused intervals separated by short breaks. This rhythm matches natural attention cycles and helps reduce mental fatigue.'},
  {id:'n48',title:'Coffee Culture',     text:'Espresso, pour-over, cold brew, and French press each extract coffee differently. Grind size, water temperature, and brew ratio determine whether the cup tastes balanced or bitter.'},
  {id:'n49',title:'Urban Gardening',    text:'Growing herbs on a windowsill or tomatoes on a balcony connects city dwellers to natural food cycles, reduces grocery costs, and provides a quiet meditative daily ritual.'},
  {id:'n50',title:'Normal Grand Finale',text:'You have practiced sentences, facts, and ideas. Now carry that rhythm into every keystroke you make. Consistency separates good typists from great ones. Keep going every single day.'}
],
hard:[
  {id:'h01',title:'Philosophical Depth',   text:'The unexamined life is not worth living — so declared Socrates at his trial in 399 BCE. Yet examination demands courage: the willingness to question everything, including one\'s most cherished beliefs, without flinching from uncomfortable answers that inevitably arise from honest inquiry.'},
  {id:'h02',title:'Microservices Arch',    text:'A microservices architecture decouples application components into independently deployable services, each responsible for a single bounded context. Communication occurs via RESTful APIs or message queues such as Kafka or RabbitMQ, depending on latency requirements and ordering guarantees needed.'},
  {id:'h03',title:'Quantum Science',       text:'Quantum entanglement describes a phenomenon whereby two particles become correlated such that the quantum state of each cannot be described independently. Measuring one particle instantaneously determines the corresponding property of the other, regardless of the spatial separation between them.'},
  {id:'h04',title:'Legal Language',        text:'The party of the first part (hereinafter referred to as "Licensor") hereby grants to the party of the second part (hereinafter "Licensee") a non-exclusive, non-transferable, revocable license to use the Software solely for internal business purposes, subject to the terms herein.'},
  {id:'h05',title:'JavaScript Memoize',    text:'const memoize = (fn) => { const cache = new Map(); return (...args) => { const key = JSON.stringify(args); if (cache.has(key)) return cache.get(key); const result = fn(...args); cache.set(key, result); return result; }; };'},
  {id:'h06',title:'Python Merge Sort',     text:'def merge_sort(arr): if len(arr) <= 1: return arr; mid = len(arr) // 2; left = merge_sort(arr[:mid]); right = merge_sort(arr[mid:]); return [*sorted([left[0], right[0]])];'},
  {id:'h07',title:'Red-Black Tree',        text:'A red-black tree maintains O(log n) height by enforcing five invariants: every node is red or black; the root is black; every leaf NIL is black; red nodes have only black children; all paths to NIL contain the same number of black nodes.'},
  {id:'h08',title:'Medical Report',        text:'The patient presented with dyspnea, tachycardia, and bilateral crackles consistent with acute decompensated heart failure. NT-proBNP levels were markedly elevated at 4,800 pg/mL, and echocardiography revealed an ejection fraction of only 25%.'},
  {id:'h09',title:'Financial Report',      text:'Q3 2024 results exceeded analyst expectations: net revenue grew 18.4% YoY to $2.37 billion, adjusted EBITDA margins expanded 340 basis points to 31.2%, and free cash flow conversion reached 112% of net income driven by working capital discipline.'},
  {id:'h10',title:'Tongue Twister 1',      text:'She sells seashells by the seashore, and the shells she sells are surely the finest seashells that have ever been sold beside a seashore anywhere in this wide and wonderful world of ours.'},
  {id:'h11',title:'Tongue Twister 2',      text:'How much wood would a woodchuck chuck if a woodchuck could chuck wood? A woodchuck would chuck as much wood as a woodchuck could chuck if a woodchuck could chuck wood every single day.'},
  {id:'h12',title:'Config Object',         text:'const config = { host: "localhost", port: 5432, db: "prod_db", ssl: true, pool: { min: 2, max: 10, idle: 30000 }, options: { schema: "public", timezone: "UTC+5:30" } };'},
  {id:'h13',title:'Regex Patterns',        text:'const emailRegex = /^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$/; const urlRegex = /^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9]{2,256}\\.[a-z]{2,6}([-a-zA-Z0-9@:%_+.~#?&=]*)$/;'},
  {id:'h14',title:'Economic Theory',       text:'According to the efficient market hypothesis, asset prices fully reflect all available information at any given moment, making it impossible to consistently achieve above-market returns without accessing superior information or bearing additional systematic risk.'},
  {id:'h15',title:'SQL Query',             text:'SELECT u.name, COUNT(o.id) AS total_orders, SUM(o.amount) AS revenue FROM users u LEFT JOIN orders o ON u.id = o.user_id WHERE o.created_at >= \'2024-01-01\' GROUP BY u.id HAVING COUNT(o.id) > 5 ORDER BY revenue DESC LIMIT 25;'},
  {id:'h16',title:'Dense Punctuation',     text:'Well — it\'s complicated, isn\'t it? "The thing is," she paused, "I don\'t know what I don\'t know." He nodded slowly; yet something — perhaps pride, perhaps fear — kept him from saying what he truly meant.'},
  {id:'h17',title:'Treaty of Westphalia',  text:'The Treaty of Westphalia (1648) established principles of modern state sovereignty, non-interference in domestic affairs, and legal equality of states — concepts that underpin contemporary international law nearly four centuries after their inception.'},
  {id:'h18',title:'CSS Animation',         text:'.hero { animation: slideIn 0.8s cubic-bezier(0.34, 1.56, 0.64, 1) forwards; } @keyframes slideIn { from { opacity: 0; transform: translateY(40px) scale(0.96); } to { opacity: 1; transform: translateY(0) scale(1); } }'},
  {id:'h19',title:'Neuroplasticity',       text:'Neuroplasticity refers to the brain\'s capacity to reorganize synaptic connections in response to learning, experience, or injury. Hebbian plasticity — "neurons that fire together wire together" — underpins long-term potentiation and memory consolidation.'},
  {id:'h20',title:'CLI Commands',          text:'git log --oneline --graph --all | head -20; docker ps -a --format "table {{.ID}}\\t{{.Names}}\\t{{.Status}}"; curl -X POST https://api.example.com/v2/data -H "Authorization: Bearer $TOKEN" -d \'{"key":"value"}\' | jq \'.result\''},
  {id:'h21',title:'Statistics Report',     text:'The 95% confidence interval for the treatment effect was 0.42 to 0.78 (p < 0.001, n = 1,247). Cohen\'s d = 0.61 indicates a medium effect size, with statistical power of 0.89 at α = 0.05. Heterogeneity was low (I² = 14.3%).'},
  {id:'h22',title:'API Request',           text:'fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "Content-Type": "application/json", "x-api-key": API_KEY }, body: JSON.stringify({ model: "claude-opus-4", max_tokens: 1024, messages: [{ role: "user", content: prompt }] }) });'},
  {id:'h23',title:'Musical Theory',        text:'The circle of fifths reveals that moving clockwise adds one sharp to the key signature (G→D→A→E→B→F#→C#), while counter-clockwise adds a flat (F→Bb→Eb→Ab→Db→Gb→Cb). Enharmonic equivalents complete the circle.'},
  {id:'h24',title:'Bosphorus Geography',   text:'The Bosphorus Strait, separating European from Asian Istanbul, is 31 km long, 700 m wide at its narrowest, and connects the Black Sea to the Sea of Marmara. Its strategic importance made it a focal point of empires for over 2,700 years.'},
  {id:'h25',title:'CQRS Pattern',          text:'The CQRS pattern separates the read model from the write model. Commands mutate state; queries retrieve data. Combined with Event Sourcing, every state change is stored as an immutable event, enabling full audit trails and temporal query capabilities.'},
  {id:'h26',title:'Dylan Thomas',          text:'"Do not go gentle into that good night, old age should burn and rave at close of day; rage, rage against the dying of the light." Thomas captured in fourteen lines what philosophers wrestle with in volumes: the imperative to fight for existence until the very last.'},
  {id:'h27',title:'Human Genome',          text:'The human genome contains approximately 3.2 x 10^9 base pairs encoding ~20,000 protein-coding genes, which represent only 1.5% of total DNA. Mitochondrial DNA adds 16,569 base pairs of circular double-stranded DNA inherited through the maternal lineage exclusively.'},
  {id:'h28',title:'Auth Endpoint',         text:'app.post("/auth/login", async (req, res) => { const { email, password } = req.body; const user = await User.findOne({ email }); if (!user || !await bcrypt.compare(password, user.hash)) return res.status(401).json({ error: "Invalid credentials" }); });'},
  {id:'h29',title:'Bitcoin Analysis',      text:'Bitcoin\'s 200-day moving average crossed above the 50-day SMA on November 3rd, generating a "golden cross" signal. RSI stands at 67.4, approaching overbought territory. On-chain metrics show exchange outflows of 42,000 BTC over 7 days.'},
  {id:'h30',title:'Dijkstra Algorithm',    text:'The asymptotic complexity of Dijkstra\'s algorithm using a binary heap is O((V + E) log V), where V represents vertices and E edges. For dense graphs where E ≈ V², a Fibonacci heap reduces this to O(E + V log V), offering significant gains in large-scale routing problems.'},
  {id:'h31',title:'TypeScript Generics',text:'function zip(a, b) { return a.map((v, i) => [v, b[i]]); } // Generic version: function zip<T, U>(a: T[], b: U[]): [T, U][]; type NonNullable<T> = T extends null | undefined ? never : T;'},
  {id:'h32',title:'Cryptography',       text:'AES-256-GCM provides confidentiality and integrity via a 128-bit authentication tag. The initialization vector must be unique per encryption; IV reuse under the same key breaks confidentiality by leaking the XOR of plaintext streams.'},
  {id:'h33',title:'Neural Networks',    text:'Backpropagation computes gradients via the chain rule. Vanishing gradients in deep networks drove adoption of ReLU activations and residual skip connections, enabling training of architectures exceeding one hundred layers with stable convergence throughout.'},
  {id:'h34',title:'Roman Principate',   text:'The Principate (27 BCE to 284 CE) preserved republican forms while concentrating power: Augustus held tribunicia potestas for life, granting sacrosanctity and veto, while proconsular imperium gave him command over the military-rich frontier provinces.'},
  {id:'h35',title:'Shell Script',       text:'#!/usr/bin/env bash; set -euo pipefail; DIR=$(cd $(dirname $0) && pwd); for f in $DIR/logs/*.log; do gzip -9 $f && mv ${f}.gz $DIR/archive/; done; echo "Archived $(find $DIR/archive -name *.gz | wc -l) files"'},
  {id:'h36',title:'Database Indexing',  text:'A composite B-tree index on (user_id, created_at) satisfies prefix queries on user_id alone but not created_at alone. A covering index eliminates heap fetches by including all projected columns, converting access patterns into cheaper index-only scans.'},
  {id:'h37',title:'Evolutionary Bio',   text:'Kin selection explains altruistic behavior through Hamilton rule: rB > C, where r is genetic relatedness, B the fitness benefit to the recipient, and C the cost to the actor. Eusocial insects satisfy this because sisters share 75 percent of genes.'},
  {id:'h38',title:'Constitutional Law', text:'Substantive due process, revived in Griswold v. Connecticut 1965 and extended in Obergefell v. Hodges 2015, holds that the Fourteenth Amendment protects unenumerated fundamental rights from state interference absent a compelling governmental interest.'},
  {id:'h39',title:'React useDebounce', text:'function useDebounce(value, delay) { const [debounced, setDebounced] = useState(value); useEffect(() => { const id = setTimeout(() => setDebounced(value), delay); return () => clearTimeout(id); }, [value, delay]); return debounced; }'},
  {id:'h40',title:'Hard Grand Finale',  text:'You have navigated philosophy, biochemistry, legal doctrine, cryptographic theory, and recursive algorithms. Every session forges new neural pathways. The distance between where you started and where you stand now is called growth. KeyZen. Keep going.'}
]
};

// ════════════════════════════════════════════════════════════════
//  Word / Quote / Code pools  (used in Words / Quotes / Code modes)
// ════════════════════════════════════════════════════════════════

const WORDS = ["the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you","do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my","one","all","would","there","their","what","so","up","out","if","about","who","get","which","go","me","when","make","can","like","time","no","just","him","know","take","people","into","year","your","good","some","could","them","see","other","than","then","now","look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way","even","new","want","because","any","these","give","day","most","us","great","large","often","hold","real","life","few","open","seem","together","next","children","begin","got","walk","ease","paper","group","always","music","book","letter","until","river","car","care","second","enough","girl","ready","above","ever","red","list","though","feel","talk","bird","soon","body","family","leave"];

const QUOTES = ["The only way to do great work is to love what you do.","In the middle of every difficulty lies opportunity.","It does not matter how slowly you go as long as you do not stop.","Life is what happens when you're busy making other plans.","The future belongs to those who believe in the beauty of their dreams.","Success is not final, failure is not fatal: it is the courage to continue that counts.","Whether you think you can or you think you can't, you're right.","I have not failed. I've just found ten thousand ways that won't work.","You miss one hundred percent of the shots you don't take.","The greatest glory in living lies not in never falling, but in rising every time we fall.","Be the change you wish to see in the world.","Spread love everywhere you go. Let no one ever come to you without leaving happier.","If life were predictable it would cease to be life and be without flavor.","You will face many defeats in life, but never let yourself be defeated.","The greatest wealth is to live content with little."];

const CODE = [
  "const greet = (name) => `Hello, ${name}!`; console.log(greet('world'));",
  "function fibonacci(n) { if (n <= 1) return n; return fibonacci(n-1) + fibonacci(n-2); }",
  "const arr = [1,2,3,4,5]; const doubled = arr.map(n => n * 2); console.log(doubled);"
];